//Autogenerated class by script: Assets/Scripts/Utilities/Editor/OpenSceneReloadMenu.cs
using UnityEngine;
using UnityEditor;

public static class OpenSceneMenu {

	[MenuItem("Open scene/0: MainMenu", false, 0)]
	static void Open0MainMenu() {
		OpenScene("Assets/_Scenes/Game/0_MainMenu.unity");
	}

	[MenuItem("Open scene/1: GrassyKnoll", false, 0)]
	static void Open1GrassyKnoll() {
		OpenScene("Assets/_Scenes/Game/1_GrassyKnoll.unity");
	}

	static void OpenScene(string scenePath) {
	if (UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) {
			UnityEditor.SceneManagement.EditorSceneManager.OpenScene(scenePath);
		}
	}
}
